services:
  web:
    image: nginx:latest
    container_name: statify-nginx-dev
    # restart: unless-stopped 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/etc/nginx/logs
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - statify-local_db
networks:
  statify-local_db:
    external: true
