-- +goose Up
-- +goose StatementBegin

CREATE TABLE "public"."analytics_events" (
  "id" bigserial NOT NULL,
  "project_id" bigint NOT NULL,
  "timestamp" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  -- Tracking Data
  "path" text NOT NULL,                -- e.g., "/docs/api-v2"
  "visitor_hash" text NOT NULL,        -- Hashed IP + UserAgent (for Unique Visitors)
  "load_time_ms" integer NULL,         -- Performance metric (stored in ms for precision)
  -- "referrer" text NULL,                -- Where they came from
  
  -- Useful for "Bounce Rate" logic
  "session_id" text NULL,              -- Optional: Generated by JS to group a single visit
  
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_analytics_project" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("id") ON DELETE CASCADE
);

-- Crucial for dashboard performance
CREATE INDEX "idx_analytics_project_timestamp" ON "public"."analytics_events" ("project_id", "timestamp");
CREATE INDEX "idx_analytics_path" ON "public"."analytics_events" ("project_id", "path");

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "public"."analytics_events";
-- +goose StatementEnd